version: '3'

services:

  vsql:
    image: probable-fiesta_vsql
    build: vsql
    expose:
           - "3306"
    volumes:
      - vdb:/var/lib/mysql
    env_file:
      - ./test.env
    
  vhttp:
    # web server for a drupal + civicrm site
    image: "probable-fiesta_vhttp:${VSITE_PHP_VERSION}-apache"
    build: 
      context: vhttp
      args:
        - VSITE_PHP_VERSION=7.0
        - DRUPAL_VERSION=7.59
        - DRUPAL_MD5=7e09c6b177345a81439fe0aa9a2d15fc
        - CIVICRM_VERSION=5.5.1

    expose:
           - "80"
    volumes:
      - vsite:/var/www/html/sites/default
    env_file:
      - ./test.env
    links:
      # access the virtual sql server as "mydb" in the /etc/hosts file
      - "vsql:mydb"
    depends_on:
      - vsql

volumes:
    vsite:
    vdb:
